### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by fineanmol** [fineanmol/Hacktoberfest2021#1]
---
name: Feature request
about: Suggest an idea for this project

---

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by samyaksand** [comment]
@fineanmol Can I contribute my Spotify Clone project which I completed - as a part of Hacktoberfest?

**Comment by fineanmol** [comment]
> @fineanmol Can I contribute my Spotify Clone project which I completed - as a part of Hacktoberfest?

Sure
