### ISSUE TITLE
"moon"/ "sun" before the dark mode toggle switch not Visible

### ISSUE THREAD

**Issue by SukritSethi** [fineanmol/Hacktoberfest2021#267]

**Comment by arunim-iiitlCS** [comment]
Hey @fineanmol can you assign me this issue under hacktoberfest tag so that ,I can work upon it.

Regards

**Comment by fineanmol** [comment]
Hi @arunim-iiitlCS , Please do your contribution and make a pull request. We would love to see your magic ✨

**Comment by YellowFoxH4XOR** [comment]
This issue was resolved and merged. PR - #300

**Comment by fineanmol** [comment]
> This issue was resolved and merged. PR - #300

No @YellowFoxH4XOR , I had to revert the code because of the case modification. It made the whole webpage layout disruptive.

**Comment by Palaksharma23** [comment]
Hii @fineanmol  I would love to work on this issue . 
Can you please provide me some reference in which file i have to add sun and moon picture

**Comment by Palaksharma23** [comment]
sun and moon icon

**Comment by arunim-iiitlCS** [comment]
Hi @fineanmol can you check my PR #440 if this issue is resolved or not.

Thanks and Regards

**Comment by Hrishabh5** [comment]
This issue is now resolved.
