### ISSUE TITLE
CSS Styling/Contributors Count of Contribution.html page is needed !

### ISSUE THREAD

**Issue by fineanmol** [fineanmol/Hacktoberfest2021#3]
> **There are many things to which you can contribute.**

- CSS Styling Needed or count of Contributors needed

- It can be the CSS styling of the webpage Contribution.html

- You can even work on the grid system of that page, to make it more wonderful

- Animation while moving the cursor over any name can be improved too

- or you can just add your name to the contributors and make a pull request.

**Comment by xevenheaven** [comment]
Added a slight improvement to the hover css! :)

**Comment by bansaljas** [comment]
I'd like to contribute. Is the still open?
This is my first time open source contribution

**Comment by fineanmol** [comment]
Yes , You can contribute in the repository! Go Ahead.

**Comment by CHANDRAMANI70** [comment]
can i contribute????

**Comment by khushali77** [comment]
Is this issue still open? Can I work on it?

**Comment by fineanmol** [comment]
> can i contribute????

Yes, You can contribute to the repository! Go Ahead

**Comment by fineanmol** [comment]
> Is this issue still open? Can I work on it?

Yes, You can contribute to the repository! Go Ahead

**Comment by fineanmol** [comment]
> Added a slight improvement to the hover css! :)

You did a beautiful Job 💯

**Comment by Palaksharma23** [comment]
hii @fineanmol i want to work on this issue , can you please assign it to me .

**Comment by fineanmol** [comment]
Hey @Palaksharma23, Please go ahead. We would love to see your contribution.
 Do the changes after fork and create a pull request from your repo. 💡

**Comment by Hermes179** [comment]
Hi, @fineanmol  I'd like to contribute to this repo but I'm confused a bit if anyone can just point out in which sections I should it'll be really helpful?

**Comment by fineanmol** [comment]
Hi @Hermes179 , Thank you for showing your interest in contribution. There are many things in which you can contribute. 

- It can be the CSS styling of the webpage Contribution.html
- You can even work on the grid system of that page, to make it more wonderful
- Animation while moving the cursor over any name can be improved too
- or you can just add your name to the contributors and make a pull request.

**Comment by osamakhan552** [comment]
Hi, @fineanmol ,Could you please assign me this issue. I am good at this and i would like to contribute to it.

**Comment by fineanmol** [comment]
hello @osamakhan552, Please do you contribution and make a pull request. Happy Coding!!

**Comment by fineanmol** [comment]
> assign me please

Hi @malburo Please do your contribution and make a pull request. Happy Coding!!

**Comment by sahilsaini110** [comment]
I would love to do this if it is still open.

**Comment by SuperAayush** [comment]
I have updated the contributor's list in Contribution.html and also made changes in text color in contribution.css and made a PR #326

**Comment by Palaksharma23** [comment]
@fineanmol  please once review this pull request . I have added text animation in word contributors in contribution.html .

**Comment by fineanmol** [comment]
> I would love to do this if it is still open.

Yes, You are welcome to make contribution

**Comment by arpit282** [comment]
Hello, Can I also contribute to this?

**Comment by fineanmol** [comment]
> Hello, Can I also contribute to this?

Yes, You are welcome to make contribution

**Comment by Devrajsinh-Jhala** [comment]
Sir @fineanmol  please assign this issue to me

**Comment by pratham1103** [comment]
I would like to change the font style and some color corrections to it, please assign this issue to me

**Comment by pratham1103** [comment]
@fineanmol  , I have added a pull request regarding the change in font style and color corrections, please do merge it and label it please !!

**Comment by pratham1103** [comment]
@fineanmol     https://github.com/fineanmol/Hacktoberfest2021/pull/603
this is my pull request

**Comment by SHIVANGISINGH1** [comment]
I would like to contribute to this project , is this still open?

**Comment by fineanmol** [comment]
> I would like to contribute to this project , is this still open?

Yes

**Comment by PaarthAgarwal** [comment]
@fineanmol #777 
This is my pull request. Please accept it under the hacktober-accepted tag. Thank you!

**Comment by Abhishek-PratapSingh** [comment]
@fineanmol please merge the file for #781
