### ISSUE TITLE
Broken live website link in readme file

### ISSUE THREAD

**Issue by gc-shisir** [fineanmol/Hacktoberfest2021#578]
the link given in readme file for live website does not work

**Comment by bidishaMondal7** [comment]
Please assign it to me. Have figured out the issue @gc-shisir

**Comment by gc-shisir** [comment]
This issue is already on the pull request pipeline @bidishaMondal7

**Comment by gc-shisir** [comment]
@bidishaMondal7 also I just came to know that this project is marked as excluded by the hacktoberfest team. So the pull request won't be counted  as valid if you want to contribute for hacktoberfest.

**Comment by gc-shisir** [comment]
> Please assign it to me. Have figured out the issue @gc-shisir

Sorry to say that I am not the maintainer of this project for assigning the issue to someone

**Comment by bidishaMondal7** [comment]
okay no problem @gc-shisir
