### ISSUE TITLE
Adding a "moon"/ "sun" before the dark mode toggle switch 

### ISSUE THREAD

**Issue by fineanmol** [fineanmol/Hacktoberfest2021#599]

**Comment by vivekarora-02** [comment]
Hey there,
I would like to contribute towards this issue. Can ypu please assign me this issue?

ThankYou!

**Comment by TD-17** [comment]
@fineanmol Hey! I would like to work on this issue! Will you please assign this issue to me ?

**Comment by bidishaMondal7** [comment]
Hi @fineanmol , 
would like to contribute on the issue. kindly assign !

**Comment by infoavsoftware** [comment]
sir i want to work on this issue for hacktoberfest 2021 as i am new but i know how we can do this!
please assign me this task kindly>>>

**Comment by Rashmisingh-18** [comment]
Hey @fineanmol, could you please assign this to me !!!

**Comment by KholoodS** [comment]
Hello is this issue up for grabs?

**Comment by vampnik** [comment]
Hey there ,
Can I work on this issue ?

**Comment by HarshJ27** [comment]
Hi sir, I am an aspiring web developer and I have a startup also in which we do web development. That's why I am confident that I can handle this issue very well. Please assign this issue to me.

**Comment by kaneki-ken260** [comment]
@fineanmol plz assign me this issue.
