### ISSUE TITLE
Sum and product of n terms of GP series in python

### ISSUE THREAD

**Issue by TheDesTrucToRR** [fineanmol/Hacktoberfest2021#717]
A python program to find the sum and product of a GP series in Python.

**Comment by TheDesTrucToRR** [comment]
@fineanmol please assing this issue to me.I want to work on it.

**Comment by TheDesTrucToRR** [comment]
@fineanmol please assign this issue to me. I want to work on it.

**Comment by gulshanjakhon** [comment]
please assign this issue to me

**Comment by gulshanjakhon** [comment]
hi please check my PR My new branch 1 #788

**Comment by Vaibhav-512** [comment]
Hi could you check my PR #774
