### ISSUE TITLE
Fibonacci sequence in C++

### ISSUE THREAD

**Issue by MiryamVicenteOllero** [fineanmol/Hacktoberfest2021#804]
Do the Fibonacci sequence in C++.
It's a series where the next term is the sum of pervious two terms.

**Comment by prakhar-198** [comment]
I'm good at resolving such issues may I please  work on this one ?...Please assign me this one.

**Comment by MiryamVicenteOllero** [comment]
Hi, sorry but I made this issue because I want to do it for the HacktoberFest.
Please, could you kindly create another issue to work on it?

**Comment by hackgone** [comment]
Can you assign this to me
